/* eslint-disable @typescript-eslint/no-require-imports -- Exercise the real SQLite/API adapters. */
require('../register-admin-typescript.cjs');
const test=require('node:test'),assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {randomUUID}=require('node:crypto');
const {OperationsStore,parseUsageBatch,analyticsFilter,logFilter}=require('../../lib/server/operations.ts');
const {RequestMonitor,trustedPeerAddress,readRequestJson}=require('../../lib/server/request-monitor.ts');
const {UsageTracker}=require('../../lib/operations/client.ts');
function fixture(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE audit_events(id TEXT PRIMARY KEY,actor TEXT,action TEXT,entity_id TEXT,created_at TEXT)');let now=Date.parse('2026-10-05T12:00:00Z');const store=new OperationsStore(db,()=>now);return {db,store,clock:()=>now,setTime:value=>now=value,close:()=>db.close()};}
const batch=(events=[{name:'page_view'}],extras={})=>({sessionId:randomUUID(),device:'desktop',locale:'en',events:events.map(event=>({id:randomUUID(),...event})),...extras});
const filter={days:7,device:'all',scope:'all'};
test('event validation retains only the documented privacy-safe schema',()=>{
  const input={...batch([{name:'search_use',target:'safe-id',query:'private query',password:'never save'}]),password:'secret',time:'1990-01-01'};
  const result=parseUsageBatch(input);assert.deepEqual(Object.keys(result).sort(),['device','events','locale','sessionId']);assert.deepEqual(Object.keys(result.events[0]).sort(),['id','name','target']);
  for(const value of [null,{}, {...input,sessionId:'bad'}, {...input,device:'smart-fridge'}, {...input,locale:'xx'}, {...input,events:[]}, {...input,events:Array(21).fill(input.events[0])}, batch([{name:'__proto__'}]), batch([{name:'search_use',target:'<script>'}])])assert.throws(()=>parseUsageBatch(value));
});
test('analytics deduplicates retried batches, counts sessions and filters traffic dimensions',()=>{
  const f=fixture();try{const value=batch([{name:'page_view'},{name:'group_select',target:'juice'},{name:'flavor_select',target:'orange'}]);assert.equal(f.store.ingest(value,'local',false),3);assert.equal(f.store.ingest(value,'local',false),0);f.store.ingest(batch([{name:'page_view'}],{device:'mobile',locale:'ar'}),'production',false);f.store.ingest(batch(),'production',true);
    const all=f.store.analytics(filter);assert.deepEqual(all.totals,{views:2,sessions:2,interactions:2,engagedSessions:1});assert.equal(all.features.length,2);assert.deepEqual(all.groups,[{id:'juice',count:1}]);assert.deepEqual(all.products,[{id:'orange',count:1}]);assert.deepEqual(f.store.analytics({...filter,scope:'production',device:'mobile'}).totals,{views:1,sessions:1,interactions:0,engagedSessions:0});assert.equal(all.trend.reduce((total,row)=>total+row.views,0),2);
    const row=f.db.prepare('SELECT * FROM ops_usage LIMIT 1').get();assert.notEqual(row.session,value.sessionId);assert.equal(row.time,f.clock());
  }finally{f.close();}
});
test('retention purges expired telemetry, including after restarting the store',()=>{const f=fixture();try{f.store.ingest(batch(),'local',false);const old=f.clock();f.setTime(old+31*86400000);const next=new OperationsStore(f.db,f.clock);assert.equal(next.analytics(filter).totals.views,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM ops_usage').get().n,0);}finally{f.close();}});
test('threshold alerts aggregate repeats, can be acknowledged, and reopen on continued activity',()=>{const f=fixture();try{for(let i=0;i<4;i++)f.store.signal('login_failed','source','/api/admin/v1/login',randomUUID());assert.equal(f.store.security().totals.openAlerts,0);f.store.signal('login_failed','source','/api/admin/v1/login',randomUUID());let alert=f.store.security().alerts[0];assert.equal(alert.count,5);f.store.acknowledge(alert.id,'owner-id');assert.equal(f.store.security().totals.openAlerts,0);assert.equal(f.store.logs({kind:'audit',severity:'all',days:1,page:1}).rows[0].action,'acknowledge:alert');f.store.signal('login_failed','source','/api/admin/v1/login',randomUUID());alert=f.store.security().alerts[0];assert.equal(alert.count,6);assert.equal(alert.acknowledgedAt,null);assert.equal(f.store.logs({kind:'security',severity:'all',days:1,page:1}).rows[0].count,6);assert.throws(()=>f.store.acknowledge('missing','owner'));}finally{f.close();}});
test('rolling thresholds expire independently of acknowledgement',()=>{const f=fixture();try{for(let i=0;i<4;i++)f.store.signal('path_probe','source','/unknown',randomUUID());assert.equal(f.store.security().totals.openAlerts,1);const before=f.clock();f.setTime(before+31*60000);f.store.signal('path_probe','source','/unknown',randomUUID());assert.equal(f.store.security().alerts.length,1);for(let i=0;i<2;i++)f.store.signal('path_probe','source','/unknown',randomUUID());assert.equal(f.store.security().alerts.length,2);}finally{f.close();}});
test('monitor blocks a flood before dispatch, emits Retry-After, safe routes and pseudonymous source',async()=>{const f=fixture();try{const monitor=new RequestMonitor(f.store,{general:2,auth:2,telemetry:2},f.clock);let dispatched=0;const run=async()=>{dispatched++;return Response.json({data:null});};const req=()=>new Request('http://localhost/api/admin/v1/catalog?password=never-log',{headers:{'X-Forwarded-For':'attacker-spoof'}});
  await monitor.handle(req(),{peerAddress:'192.0.2.1'},null,run);await monitor.handle(req(),{peerAddress:'192.0.2.1'},null,run);const result=await monitor.handle(req(),{peerAddress:'192.0.2.1'},null,run);assert.equal(result.status,429);assert.equal(dispatched,2);assert.equal(result.headers.get('Retry-After'),'60');assert.match(result.headers.get('X-Request-ID'),/^[a-f0-9-]{36}$/);assert.equal(f.store.security().totals.openAlerts,1);const json=JSON.stringify(f.store.logs({kind:'request',severity:'all',days:1,page:1}));assert.ok(!json.includes('never-log'));assert.ok(!json.includes('192.0.2.1'));assert.ok(!json.includes('attacker-spoof'));f.setTime(f.clock()+61000);assert.equal((await monitor.handle(req(),{peerAddress:'192.0.2.1'},null,run)).status,200);
}finally{f.close();}});
test('monitor detects repeated probing, payload errors, failed auth and 5xx',async()=>{const f=fixture();try{const monitor=new RequestMonitor(f.store);for(const [url,status,code] of [['/api/admin/v1/.env',404,'NOT_FOUND'],['/api/admin/v1/login',401,'UNAUTHORIZED'],['/api/admin/v1/catalog',500,'SERVER_ERROR'],['/api/public/v1/events',422,'INVALID_TELEMETRY']])for(let i=0;i<10;i++)await monitor.handle(new Request(`http://localhost${url}?secret=hidden`),{peerAddress:url},null,async()=>Response.json({error:{code}},{status}));const types=f.store.security().alerts.map(row=>row.type);for(const type of ['path_probe','login_failed','server_error','invalid_payload'])assert.ok(types.includes(type),type);assert.ok(f.store.logs({kind:'request',severity:'critical',days:1,page:1}).rows.every(row=>row.status>=500));}finally{f.close();}});
test('logging failures preserve the original response and expose degraded monitoring',async()=>{const f=fixture();try{const monitor=new RequestMonitor(f.store);f.store.request=()=>{throw Error('disk full');};assert.equal((await monitor.handle(new Request('http://localhost/api/admin/v1/catalog'),{},null,async()=>new Response('okay'))).status,200);assert.equal(f.store.security().monitoring,'degraded');}finally{f.close();}});
test('bounded JSON parser rejects large payloads with and without Content-Length',async()=>{const large=new Request('http://localhost/api/admin/v1/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:'x'.repeat(9000)})});await assert.rejects(()=>readRequestJson(large),error=>error.code==='PAYLOAD_TOO_LARGE');await assert.rejects(()=>readRequestJson(new Request('http://localhost/api/public/v1/events',{method:'POST',headers:{'Content-Type':'application/json'},body:'not json'})),error=>error.code==='INVALID_JSON');const f=fixture();try{let run=false;const monitor=new RequestMonitor(f.store);const response=await monitor.handle(new Request('http://localhost/api/admin/v1/login',{method:'POST',headers:{'Content-Length':'99999'},body:'{}'}),{},null,async()=>{run=true;return new Response();});assert.equal(response.status,413);assert.equal(run,false);}finally{f.close();}});
test('only explicitly trusted proxies can supply client IP and hostile filters are rejected',()=>{assert.equal(trustedPeerAddress('127.0.0.1','203.0.113.1',new Set()),'127.0.0.1');assert.equal(trustedPeerAddress('::ffff:127.0.0.1','198.51.100.2, 203.0.113.1',new Set(['127.0.0.1'])),'203.0.113.1');assert.equal(trustedPeerAddress('127.0.0.1','evil',new Set(['127.0.0.1'])),'127.0.0.1');for(const params of ['days=999','device=__proto__','scope=anything'])assert.throws(()=>analyticsFilter(new URLSearchParams(params)));for(const params of ['kind=ops_meta','severity=anything','page=-1','page=1.5','days=999'])assert.throws(()=>logFilter(new URLSearchParams(params)));});
test('paginated logs and exported logs are bounded and filters actually change returned data',()=>{const f=fixture();try{for(let i=0;i<65;i++)f.store.request({id:randomUUID(),route:'/api/admin/v1/catalog',method:'GET',status:i%2?200:500,duration:2,source:'hash'});const first=f.store.logs({kind:'request',severity:'all',days:1,page:1}),second=f.store.logs({kind:'request',severity:'all',days:1,page:2});assert.equal(first.rows.length,50);assert.equal(second.rows.length,15);assert.equal(first.total,65);assert.equal(f.store.logs({kind:'request',severity:'critical',days:1,page:1}).total,33);assert.equal(f.store.logs({kind:'request',severity:'all',days:1,page:1},true).rows.length,65);}finally{f.close();}});
test('client tracker deduplicates StrictMode page views, retries event IDs, excludes private targets and opt-outs',async()=>{const memory=new Map();let now=0,disabled=false,succeed=false;const sent=[];const tracker=new UsageTracker({now:()=>now,uuid:randomUUID,storage:{getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value)},disabled:()=>disabled,device:()=> 'mobile',send:async value=>{sent.push(value);return succeed;}});tracker.track('page_view');tracker.track('page_view');tracker.track('search_use','private query with spaces');tracker.setLocale('fr');await tracker.flush();assert.equal(sent[0].events.length,2);assert.equal(sent[0].events[1].target,undefined);succeed=true;await tracker.flush();assert.equal(sent[0].events[0].id,sent[1].events[0].id);assert.equal(sent[1].locale,'en','A queued event keeps the language at the time of the action');disabled=true;tracker.track('favorite');await tracker.flush();assert.equal(sent.length,2);disabled=false;now=31*60000;tracker.track('page_view');await tracker.flush();assert.notEqual(sent[1].sessionId,sent[2].sessionId);});
