import type { Locale } from './catalog';

interface CollectionCopy { allProducts: string; seeAll: string; netContent: string; previous: string; next: string; page: string; drinkTypes: string; allDrinks: string; allLines: string; back: string; browse: string; viewProduct: string; clear: string }
const copies: Record<Locale, CollectionCopy> = {
  en: { allProducts: 'See all products', seeAll: 'See all', netContent: 'Net content', previous: 'Previous', next: 'Next', page: 'Page {current} of {total}', drinkTypes: 'Beverage types', allDrinks: 'All beverages', allLines: 'All product lines', back: 'Back to home', browse: 'Every flavor. One collection.', viewProduct: 'View product', clear: 'Clear filters' },
  fr: { allProducts: 'Voir tous les produits', seeAll: 'Voir tout', netContent: 'Contenu net', previous: 'Précédent', next: 'Suivant', page: 'Page {current} sur {total}', drinkTypes: 'Types de boissons', allDrinks: 'Toutes les boissons', allLines: 'Toutes les gammes', back: 'Retour à l’accueil', browse: 'Toutes les saveurs. Une collection.', viewProduct: 'Voir le produit', clear: 'Effacer les filtres' },
  zh: { allProducts: '查看所有产品', seeAll: '查看详情', netContent: '净含量', previous: '上一页', next: '下一页', page: '第 {current} 页，共 {total} 页', drinkTypes: '饮料类别', allDrinks: '所有饮料', allLines: '所有产品系列', back: '返回首页', browse: '每一种风味，同一个系列。', viewProduct: '查看产品', clear: '清除筛选' },
  es: { allProducts: 'Ver todos los productos', seeAll: 'Ver más', netContent: 'Contenido neto', previous: 'Anterior', next: 'Siguiente', page: 'Página {current} de {total}', drinkTypes: 'Tipos de bebidas', allDrinks: 'Todas las bebidas', allLines: 'Todas las líneas', back: 'Volver al inicio', browse: 'Todos los sabores. Una colección.', viewProduct: 'Ver producto', clear: 'Borrar filtros' },
  ar: { allProducts: 'عرض جميع المنتجات', seeAll: 'عرض المزيد', netContent: 'المحتوى الصافي', previous: 'السابق', next: 'التالي', page: 'الصفحة {current} من {total}', drinkTypes: 'أنواع المشروبات', allDrinks: 'جميع المشروبات', allLines: 'جميع خطوط المنتجات', back: 'العودة إلى الرئيسية', browse: 'كل النكهات. مجموعة واحدة.', viewProduct: 'عرض المنتج', clear: 'مسح المرشحات' },
  ru: { allProducts: 'Все продукты', seeAll: 'Подробнее', netContent: 'Объём', previous: 'Назад', next: 'Далее', page: 'Страница {current} из {total}', drinkTypes: 'Виды напитков', allDrinks: 'Все напитки', allLines: 'Все линейки', back: 'На главную', browse: 'Все вкусы. Одна коллекция.', viewProduct: 'Посмотреть продукт', clear: 'Сбросить фильтры' },
  ko: { allProducts: '모든 제품 보기', seeAll: '자세히 보기', netContent: '내용량', previous: '이전', next: '다음', page: '{total}페이지 중 {current}페이지', drinkTypes: '음료 종류', allDrinks: '모든 음료', allLines: '모든 제품군', back: '홈으로 돌아가기', browse: '모든 맛을 한곳에서.', viewProduct: '제품 보기', clear: '필터 초기화' },
  de: { allProducts: 'Alle Produkte ansehen', seeAll: 'Mehr ansehen', netContent: 'Nettofüllmenge', previous: 'Zurück', next: 'Weiter', page: 'Seite {current} von {total}', drinkTypes: 'Getränkearten', allDrinks: 'Alle Getränke', allLines: 'Alle Produktlinien', back: 'Zur Startseite', browse: 'Alle Geschmacksrichtungen. Eine Kollektion.', viewProduct: 'Produkt ansehen', clear: 'Filter zurücksetzen' },
};
export const collectionCopy = (locale: Locale) => copies[locale];
