import type { Locale } from './catalog';

const english = {
  open: 'Open Mockup Studio', back: 'Back to website', title: 'Mockup Studio', eyebrow: 'Your product. Your perspective.',
  intro: 'Choose a package, find its label and make it yours.', library: 'Product library', models: 'Models', presets: '3D presets', labels: 'Labels',
  search: 'Search the library', searchPlaceholder: 'Search name or flavor…', packaging: 'Packaging', volume: 'Volume', drink: 'Drink category', all: 'All',
  clear: 'Clear filters', results: 'results', noResults: 'No matches for these filters', tryFilters: 'Try another search or clear your filters.',
  noLabels: 'No compatible labels yet', noLabelsCopy: 'You can explore and export this package without a label. Try another model to discover more designs.',
  blank: 'Without label', removeLabel: 'Remove label', compatible: 'Compatible labels', previous: 'Previous page', next: 'Next page', page: 'Page', of: 'of',
  focal: 'Focal length', front: 'Front', backView: 'Back', left: 'Left', right: 'Right', threeQuarter: '3/4 view', top: 'Top angle',
  background: 'Background', white: 'White', gray: 'Gray', dark: 'Dark', color: 'Color', gradient: 'Gradient', transparent: 'Transparent', colorStart: 'Background color', colorEnd: 'Gradient end color',
  animation: 'Motion', off: 'Still', turntable: 'Rotate product', showcase: 'Website mode', play: 'Play animation', pause: 'Pause animation', speed: 'Speed',
  zoomIn: 'Zoom in', zoomOut: 'Zoom out', reset: 'Reset view', hint: 'Drag to explore · Scroll to zoom', keyboard: 'Use arrow keys to rotate, + or − to zoom and R to reset.',
  export: 'Export image', frame: 'Image frame', square: 'Square', portrait: 'Portrait', landscape: 'Landscape', resolution: 'Resolution', download: 'Download PNG',
  exportCopy: 'Your current view, ready to share.', transparentCopy: 'PNG exports with a transparent background; the studio backdrop is not included.',
  preparing: 'Preparing your scene…', loadingModel: 'Loading model…', loadingLabel: 'Applying label…', ready: 'Ready to export', exporting: 'Creating your PNG…',
  loadError: 'The library could not be loaded.', sceneError: 'This scene could not be prepared.', webglError: '3D is unavailable in this browser. Try another browser or return to the website.',
  exportError: 'The image could not be exported. Try 1024 px or retry.', retry: 'Try again', downloaded: 'Your PNG is ready. The download has started.',
  unavailable: 'The requested design is unavailable in this library. A published design has been selected.', incompatible: 'This label does not fit the selected package. Choose a compatible label below.',
  empty: 'The Mockup library is not available yet.', emptyCopy: 'Visit the website to explore the published collection.', newRelease: 'A new product library is available.', reload: 'Load new library',
  release: 'Public library', model: 'Model', label: 'Label', selected: 'Selected', help: 'View controls',
  lastImage: 'Last exported image', downloadAgain: 'Download PNG again', viewImage: 'Open the exported PNG',
  ultraWide: 'Ultra wide', wide: 'Wide', standard: 'Standard', long: 'Long', telephoto: 'Telephoto',
};
export type MockupCopy = { [Key in keyof typeof english]: string };

function translated(values: string[]): MockupCopy {
  const keys = Object.keys(english) as (keyof MockupCopy)[];
  if (values.length !== keys.length) throw new Error('Incomplete Mockup Studio translation.');
  return Object.fromEntries(keys.map((key, index) => [key, values[index]])) as MockupCopy;
}

export const mockupCopy: Record<Locale, MockupCopy> = {
  en: english,
  fr: translated([
    'Ouvrir le studio Mockup','Retour au site','Studio Mockup','Votre produit. Votre point de vue.','Choisissez un emballage et son étiquette, puis créez votre image.','Bibliothèque de produits','Modèles','Préréglages 3D','Étiquettes','Rechercher dans la bibliothèque','Rechercher un nom ou une saveur…','Emballage','Volume','Catégorie de boisson','Tous','Effacer les filtres','résultats','Aucun résultat pour ces filtres','Essayez une autre recherche ou effacez les filtres.','Aucune étiquette compatible','Vous pouvez explorer et exporter cet emballage sans étiquette. Essayez un autre modèle pour découvrir davantage de designs.','Sans étiquette','Retirer l’étiquette','Étiquettes compatibles','Page précédente','Page suivante','Page','sur','Focale','Face','Dos','Gauche','Droite','Vue 3/4','Vue plongeante','Arrière-plan','Blanc','Gris','Sombre','Couleur','Dégradé','Transparent','Couleur de fond','Couleur finale du dégradé','Mouvement','Immobile','Tourner le produit','Mode site','Lancer l’animation','Mettre en pause','Vitesse','Zoom avant','Zoom arrière','Réinitialiser la vue','Glissez pour explorer · Faites défiler pour zoomer','Utilisez les flèches pour orbiter, + ou − pour zoomer et R pour réinitialiser.','Exporter l’image','Format de l’image','Carré','Portrait','Paysage','Résolution','Télécharger le PNG','Votre vue actuelle, prête à partager.','Le PNG aura un fond transparent, sans le décor du studio.','Préparation de la scène…','Chargement du modèle…','Application de l’étiquette…','Prêt à exporter','Création du PNG…','Impossible de charger la bibliothèque.','Impossible de préparer cette scène.','La 3D n’est pas disponible dans ce navigateur. Essayez un autre navigateur ou retournez au site.','Impossible d’exporter l’image. Essayez 1024 px ou réessayez.','Réessayer','Votre PNG est prêt. Le téléchargement a démarré.','Le design demandé n’est pas disponible. Un design publié a été sélectionné.','Cette étiquette ne convient pas à cet emballage. Choisissez une étiquette compatible.','La bibliothèque Mockup n’est pas encore disponible.','Visitez le site pour découvrir la collection publiée.','Une nouvelle bibliothèque est disponible.','Charger la bibliothèque','Bibliothèque publique','Modèle','Étiquette','Sélectionné','Commandes de la vue','Dernière image exportée','Télécharger à nouveau le PNG','Ouvrir le PNG exporté',
    'Ultra grand-angle','Grand-angle','Standard','Longue','Téléobjectif',
  ]),
  zh: translated([
    '打开样机工作室','返回网站','样机工作室','您的产品，您的视角。','选择包装和标签，打造专属图片。','产品库','模型','3D 预设','标签','搜索产品库','搜索名称或口味…','包装','容量','饮品类别','全部','清除筛选','个结果','没有符合筛选的结果','请尝试其他搜索或清除筛选。','暂无兼容标签','您可以查看并导出不带标签的包装。选择其他模型，探索更多设计。','无标签','移除标签','兼容标签','上一页','下一页','第','共','焦距','正面','背面','左侧','右侧','3/4 视角','俯斜视角','背景','白色','灰色','深色','颜色','渐变','透明','背景颜色','渐变结束颜色','动态','静止','旋转产品','网站模式','播放动画','暂停动画','速度','放大','缩小','重置视角','拖动探索 · 滚动缩放','使用方向键环绕，+ 或 − 缩放，R 重置。','导出图片','图片比例','正方形','竖向','横向','分辨率','下载 PNG','将当前视角变成可分享的图片。','PNG 将使用透明背景，不包含工作室背景。','正在准备场景…','正在加载模型…','正在应用标签…','可以导出','正在创建 PNG…','无法加载产品库。','无法准备此场景。','此浏览器无法显示 3D。请尝试其他浏览器或返回网站。','无法导出图片。请尝试 1024 像素或重试。','重试','您的 PNG 已准备好，下载已开始。','请求的设计在此产品库中不可用。已选择一个已发布的设计。','此标签不适合所选包装。请在下方选择兼容标签。','样机产品库暂不可用。','访问网站，探索已发布的产品系列。','新的产品库已上线。','加载新产品库','公开产品库','模型','标签','已选择','视角控制','最近导出的图片','重新下载 PNG','打开导出的 PNG',
    '超广角','广角','标准','长焦','远摄',
  ]),
  es: translated([
    'Abrir el estudio de mockups','Volver al sitio','Estudio de mockups','Tu producto. Tu perspectiva.','Elige un envase y su etiqueta y crea tu imagen.','Biblioteca de productos','Modelos','Preajustes 3D','Etiquetas','Buscar en la biblioteca','Buscar nombre o sabor…','Envase','Volumen','Categoría de bebida','Todos','Borrar filtros','resultados','Sin resultados para estos filtros','Prueba otra búsqueda o borra los filtros.','Todavía no hay etiquetas compatibles','Puedes explorar y exportar este envase sin etiqueta. Prueba otro modelo para descubrir más diseños.','Sin etiqueta','Quitar etiqueta','Etiquetas compatibles','Página anterior','Página siguiente','Página','de','Focal','Frente','Parte trasera','Izquierda','Derecha','Vista 3/4','Ángulo superior','Fondo','Blanco','Gris','Oscuro','Color','Degradado','Transparente','Color de fondo','Color final del degradado','Movimiento','Estático','Girar producto','Modo web','Reproducir animación','Pausar animación','Velocidad','Acercar','Alejar','Restablecer vista','Arrastra para explorar · Desplázate para ampliar','Usa las flechas para orbitar, + o − para ampliar y R para restablecer.','Exportar imagen','Formato de imagen','Cuadrado','Vertical','Horizontal','Resolución','Descargar PNG','Tu vista actual, lista para compartir.','El PNG tendrá un fondo transparente, sin el fondo del estudio.','Preparando la escena…','Cargando modelo…','Aplicando etiqueta…','Listo para exportar','Creando tu PNG…','No se pudo cargar la biblioteca.','No se pudo preparar esta escena.','La vista 3D no está disponible en este navegador. Prueba otro o vuelve al sitio.','No se pudo exportar la imagen. Prueba con 1024 px o inténtalo de nuevo.','Reintentar','Tu PNG está listo. La descarga ha comenzado.','El diseño solicitado no está disponible. Se ha seleccionado un diseño publicado.','Esta etiqueta no encaja en el envase. Elige una etiqueta compatible.','La biblioteca de mockups todavía no está disponible.','Visita el sitio para explorar la colección publicada.','Hay una nueva biblioteca disponible.','Cargar nueva biblioteca','Biblioteca pública','Modelo','Etiqueta','Seleccionado','Controles de vista','Última imagen exportada','Volver a descargar PNG','Abrir el PNG exportado',
    'Ultra amplio','Amplio','Estándar','Largo','Telefoto',
  ]),
  ar: translated([
    'فتح استوديو النماذج','العودة إلى الموقع','استوديو النماذج','منتجك. رؤيتك.','اختر العبوة والملصق وأنشئ صورتك.','مكتبة المنتجات','النماذج','إعدادات ثلاثية الأبعاد','الملصقات','البحث في المكتبة','ابحث بالاسم أو النكهة…','العبوة','الحجم','فئة المشروب','الكل','مسح عوامل التصفية','نتائج','لا توجد نتائج لهذه التصفية','جرّب بحثًا آخر أو امسح عوامل التصفية.','لا توجد ملصقات متوافقة بعد','يمكنك استكشاف هذه العبوة وتصديرها دون ملصق. جرّب نموذجًا آخر لاكتشاف المزيد من التصاميم.','دون ملصق','إزالة الملصق','الملصقات المتوافقة','الصفحة السابقة','الصفحة التالية','صفحة','من','البعد البؤري','الأمام','الخلف','اليسار','اليمين','زاوية 3/4','زاوية علوية','الخلفية','أبيض','رمادي','داكن','لون','تدرّج','شفافة','لون الخلفية','اللون الأخير للتدرّج','الحركة','ثابت','تدوير المنتج','وضع الموقع','تشغيل الحركة','إيقاف الحركة مؤقتًا','السرعة','تكبير','تصغير','إعادة ضبط العرض','اسحب للاستكشاف · مرّر للتكبير','استخدم الأسهم للدوران و+ أو − للتكبير وR لإعادة الضبط.','تصدير الصورة','إطار الصورة','مربع','عمودي','أفقي','الدقة','تنزيل PNG','عرضك الحالي جاهز للمشاركة.','ستكون خلفية PNG شفافة، دون خلفية الاستوديو.','جارٍ إعداد المشهد…','جارٍ تحميل النموذج…','جارٍ تطبيق الملصق…','جاهز للتصدير','جارٍ إنشاء PNG…','تعذّر تحميل المكتبة.','تعذّر إعداد هذا المشهد.','العرض ثلاثي الأبعاد غير متاح في هذا المتصفح. جرّب متصفحًا آخر أو عُد إلى الموقع.','تعذّر تصدير الصورة. جرّب 1024 بكسل أو أعد المحاولة.','إعادة المحاولة','صورة PNG جاهزة. بدأ التنزيل.','التصميم المطلوب غير متاح في هذه المكتبة. تم اختيار تصميم منشور.','هذا الملصق لا يناسب العبوة. اختر ملصقًا متوافقًا أدناه.','مكتبة النماذج غير متاحة بعد.','زر الموقع لاستكشاف المجموعة المنشورة.','تتوفر مكتبة منتجات جديدة.','تحميل المكتبة الجديدة','المكتبة العامة','نموذج','ملصق','محدد','عناصر التحكم بالعرض','آخر صورة تم تصديرها','تنزيل PNG مرة أخرى','فتح صورة PNG المصدّرة',
    'واسع جدًا','واسع','قياسي','طويل','تقريب',
  ]),
  ru: translated([
    'Открыть студию макетов','Вернуться на сайт','Студия макетов','Ваш продукт. Ваш ракурс.','Выберите упаковку и этикетку и создайте своё изображение.','Библиотека продуктов','Модели','3D-пресеты','Этикетки','Поиск в библиотеке','Поиск по названию или вкусу…','Упаковка','Объём','Категория напитка','Все','Сбросить фильтры','результатов','Нет результатов для этих фильтров','Попробуйте другой запрос или сбросьте фильтры.','Совместимых этикеток пока нет','Вы можете просмотреть и экспортировать упаковку без этикетки. Выберите другую модель для новых дизайнов.','Без этикетки','Убрать этикетку','Совместимые этикетки','Предыдущая страница','Следующая страница','Страница','из','Фокус','Спереди','Сзади','Слева','Справа','Ракурс 3/4','Сверху под углом','Фон','Белый','Серый','Тёмный','Цвет','Градиент','Прозрачный','Цвет фона','Конечный цвет градиента','Движение','Статично','Вращать продукт','Режим сайта','Запустить анимацию','Приостановить анимацию','Скорость','Приблизить','Отдалить','Сбросить ракурс','Перетащите для обзора · Прокрутите для масштаба','Используйте стрелки для вращения, + или − для масштаба и R для сброса.','Экспорт изображения','Формат изображения','Квадрат','Портрет','Альбом','Разрешение','Скачать PNG','Ваш текущий ракурс, готовый к публикации.','PNG будет с прозрачным фоном, без фона студии.','Подготовка сцены…','Загрузка модели…','Применение этикетки…','Готово к экспорту','Создание PNG…','Не удалось загрузить библиотеку.','Не удалось подготовить сцену.','3D недоступно в этом браузере. Попробуйте другой браузер или вернитесь на сайт.','Не удалось экспортировать изображение. Попробуйте 1024 пикселя или повторите попытку.','Повторить','Ваш PNG готов. Загрузка началась.','Запрошенный дизайн недоступен. Выбран опубликованный дизайн.','Этикетка не подходит к упаковке. Выберите совместимую этикетку ниже.','Библиотека макетов пока недоступна.','Посетите сайт, чтобы посмотреть опубликованную коллекцию.','Доступна новая библиотека продуктов.','Загрузить новую библиотеку','Публичная библиотека','Модель','Этикетка','Выбрано','Управление ракурсом','Последнее экспортированное изображение','Скачать PNG ещё раз','Открыть экспортированный PNG',
    'Сверхширокий','Широкий','Стандарт','Длинный','Телефото',
  ]),
  ko: translated([
    '목업 스튜디오 열기','웹사이트로 돌아가기','목업 스튜디오','당신의 제품, 당신의 시선.','패키지와 라벨을 선택하고 나만의 이미지를 만드세요.','제품 라이브러리','모델','3D 프리셋','라벨','라이브러리 검색','이름 또는 맛 검색…','패키지','용량','음료 카테고리','전체','필터 초기화','개 결과','필터에 맞는 결과가 없습니다','다른 검색어를 사용하거나 필터를 초기화하세요.','호환되는 라벨이 아직 없습니다','라벨 없이 패키지를 살펴보고 내보낼 수 있습니다. 다른 모델에서 더 많은 디자인을 찾아보세요.','라벨 없음','라벨 제거','호환 라벨','이전 페이지','다음 페이지','페이지','/','초점 거리','정면','후면','왼쪽','오른쪽','3/4 보기','상단 각도','배경','흰색','회색','어두움','색상','그라데이션','투명','배경 색상','그라데이션 끝 색상','움직임','정지','제품 회전','웹사이트 모드','애니메이션 재생','애니메이션 일시 정지','속도','확대','축소','뷰 초기화','드래그하여 둘러보기 · 스크롤하여 확대','방향키로 회전, + 또는 −로 확대, R로 초기화하세요.','이미지 내보내기','이미지 비율','정사각형','세로','가로','해상도','PNG 다운로드','현재 화면을 공유할 수 있는 이미지로.','PNG는 스튜디오 배경 없이 투명 배경으로 저장됩니다.','장면 준비 중…','모델 로딩 중…','라벨 적용 중…','내보내기 준비 완료','PNG 생성 중…','라이브러리를 불러올 수 없습니다.','이 장면을 준비할 수 없습니다.','이 브라우저에서는 3D를 사용할 수 없습니다. 다른 브라우저를 사용하거나 웹사이트로 돌아가세요.','이미지를 내보낼 수 없습니다. 1024 px를 선택하거나 다시 시도하세요.','다시 시도','PNG가 준비되었습니다. 다운로드가 시작되었습니다.','요청한 디자인을 사용할 수 없어 공개된 디자인을 선택했습니다.','이 라벨은 선택한 패키지에 맞지 않습니다. 아래에서 호환 라벨을 선택하세요.','목업 라이브러리가 아직 준비되지 않았습니다.','웹사이트에서 공개된 컬렉션을 둘러보세요.','새 제품 라이브러리를 사용할 수 있습니다.','새 라이브러리 불러오기','공개 라이브러리','모델','라벨','선택됨','뷰 조작','최근 내보낸 이미지','PNG 다시 다운로드','내보낸 PNG 열기',
    '초광각','광각','표준','장초점','망원',
  ]),
  de: translated([
    'Mockup-Studio öffnen','Zurück zur Website','Mockup-Studio','Dein Produkt. Deine Perspektive.','Wähle eine Verpackung und ein Etikett und gestalte dein Bild.','Produktbibliothek','Modelle','3D-Vorlagen','Etiketten','Bibliothek durchsuchen','Name oder Geschmack suchen…','Verpackung','Volumen','Getränkekategorie','Alle','Filter zurücksetzen','Ergebnisse','Keine passenden Ergebnisse','Versuche eine andere Suche oder setze die Filter zurück.','Noch keine passenden Etiketten','Du kannst diese Verpackung ohne Etikett ansehen und exportieren. Entdecke weitere Designs mit einem anderen Modell.','Ohne Etikett','Etikett entfernen','Passende Etiketten','Vorherige Seite','Nächste Seite','Seite','von','Brennweite','Vorne','Hinten','Links','Rechts','3/4-Ansicht','Schräg von oben','Hintergrund','Weiß','Grau','Dunkel','Farbe','Verlauf','Transparent','Hintergrundfarbe','Endfarbe des Verlaufs','Bewegung','Still','Produkt drehen','Website-Modus','Animation abspielen','Animation pausieren','Geschwindigkeit','Vergrößern','Verkleinern','Ansicht zurücksetzen','Ziehen zum Erkunden · Scrollen zum Zoomen','Mit Pfeiltasten drehen, mit + oder − zoomen und mit R zurücksetzen.','Bild exportieren','Bildformat','Quadrat','Hochformat','Querformat','Auflösung','PNG herunterladen','Deine aktuelle Ansicht, bereit zum Teilen.','Das PNG erhält einen transparenten Hintergrund, ohne den Studiohintergrund.','Szene wird vorbereitet…','Modell wird geladen…','Etikett wird angewendet…','Bereit zum Exportieren','PNG wird erstellt…','Die Bibliothek konnte nicht geladen werden.','Diese Szene konnte nicht vorbereitet werden.','3D ist in diesem Browser nicht verfügbar. Versuche einen anderen Browser oder kehre zur Website zurück.','Das Bild konnte nicht exportiert werden. Versuche 1024 px oder erneut.','Erneut versuchen','Dein PNG ist bereit. Der Download wurde gestartet.','Das gewünschte Design ist nicht verfügbar. Ein veröffentlichtes Design wurde ausgewählt.','Dieses Etikett passt nicht zur Verpackung. Wähle unten ein passendes Etikett.','Die Mockup-Bibliothek ist noch nicht verfügbar.','Besuche die Website und entdecke die veröffentlichte Kollektion.','Eine neue Produktbibliothek ist verfügbar.','Neue Bibliothek laden','Öffentliche Bibliothek','Modell','Etikett','Ausgewählt','Ansichtssteuerung','Zuletzt exportiertes Bild','PNG erneut herunterladen','Exportiertes PNG öffnen',
    'Ultraweit','Weit','Standard','Lang','Tele',
  ]),
};
