import type { Locale } from './catalog';

interface DetailCopy { story: string; ingredients: string; nutrition: string; productInfo: string; serving: string; nutrient: string; amount: string; daily: string; allergens: string; manufacturer: string; origin: string; volume: string; storage: string; shelfLife: string; notProvided: string; collection: string; close: string }
const copies: Record<Locale, DetailCopy> = {
  en: { story: 'The story', ingredients: 'Ingredients', nutrition: 'Nutrition facts', productInfo: 'Product information', serving: 'Serving basis', nutrient: 'Nutrient', amount: 'Amount', daily: 'Daily value', allergens: 'Allergen information', manufacturer: 'Made by', origin: 'Country of origin', volume: 'Net content', storage: 'Storage & enjoyment', shelfLife: 'Shelf life', notProvided: 'Information not yet provided.', collection: 'The fruit collection', close: 'Close product details' },
  fr: { story: 'L’histoire', ingredients: 'Ingrédients', nutrition: 'Valeurs nutritionnelles', productInfo: 'Informations produit', serving: 'Base de calcul', nutrient: 'Nutriment', amount: 'Quantité', daily: 'Valeur quotidienne', allergens: 'Allergènes', manufacturer: 'Fabricant', origin: 'Pays d’origine', volume: 'Contenu net', storage: 'Conservation et dégustation', shelfLife: 'Durée de conservation', notProvided: 'Information pas encore renseignée.', collection: 'La collection fruitée', close: 'Fermer les détails du produit' },
  zh: { story: '产品介绍', ingredients: '配料', nutrition: '营养成分', productInfo: '产品信息', serving: '计量基准', nutrient: '营养素', amount: '含量', daily: '每日参考值', allergens: '过敏原信息', manufacturer: '生产商', origin: '原产国', volume: '净含量', storage: '储存与饮用', shelfLife: '保质期', notProvided: '信息尚未提供。', collection: '水果系列', close: '关闭产品详情' },
  es: { story: 'La historia', ingredients: 'Ingredientes', nutrition: 'Información nutricional', productInfo: 'Información del producto', serving: 'Base de cálculo', nutrient: 'Nutriente', amount: 'Cantidad', daily: 'Valor diario', allergens: 'Alérgenos', manufacturer: 'Fabricado por', origin: 'País de origen', volume: 'Contenido neto', storage: 'Conservación y consumo', shelfLife: 'Vida útil', notProvided: 'Información aún no disponible.', collection: 'La colección de frutas', close: 'Cerrar detalles del producto' },
  ar: { story: 'القصة', ingredients: 'المكونات', nutrition: 'القيم الغذائية', productInfo: 'معلومات المنتج', serving: 'أساس القياس', nutrient: 'العنصر الغذائي', amount: 'الكمية', daily: 'القيمة اليومية', allergens: 'معلومات مسببات الحساسية', manufacturer: 'الشركة المصنعة', origin: 'بلد المنشأ', volume: 'المحتوى الصافي', storage: 'التخزين والاستهلاك', shelfLife: 'مدة الصلاحية', notProvided: 'المعلومات غير متوفرة بعد.', collection: 'مجموعة الفواكه', close: 'إغلاق تفاصيل المنتج' },
  ru: { story: 'О продукте', ingredients: 'Состав', nutrition: 'Пищевая ценность', productInfo: 'Информация о продукте', serving: 'Основа расчёта', nutrient: 'Показатель', amount: 'Количество', daily: 'Суточная норма', allergens: 'Аллергены', manufacturer: 'Производитель', origin: 'Страна происхождения', volume: 'Объём', storage: 'Хранение и употребление', shelfLife: 'Срок годности', notProvided: 'Информация ещё не указана.', collection: 'Фруктовая коллекция', close: 'Закрыть информацию о продукте' },
  ko: { story: '제품 이야기', ingredients: '원재료', nutrition: '영양정보', productInfo: '제품 정보', serving: '영양정보 기준', nutrient: '영양소', amount: '함량', daily: '일일 기준치', allergens: '알레르기 정보', manufacturer: '제조사', origin: '원산지', volume: '내용량', storage: '보관 및 음용 방법', shelfLife: '소비기한', notProvided: '아직 제공되지 않은 정보입니다.', collection: '과일 컬렉션', close: '제품 상세 닫기' },
  de: { story: 'Die Geschichte', ingredients: 'Zutaten', nutrition: 'Nährwertangaben', productInfo: 'Produktinformationen', serving: 'Bezugsmenge', nutrient: 'Nährstoff', amount: 'Menge', daily: 'Tageswert', allergens: 'Allergeninformationen', manufacturer: 'Hergestellt von', origin: 'Herkunftsland', volume: 'Nettofüllmenge', storage: 'Lagerung und Genuss', shelfLife: 'Haltbarkeit', notProvided: 'Information noch nicht verfügbar.', collection: 'Die Fruchtkollektion', close: 'Produktdetails schließen' },
};
export const productDetailCopy = (locale: Locale) => copies[locale];
