import type { Locale } from './catalog';

interface Copy { name: string; on: string; off: string; waiting: string; core: string; effects: string; error: string; retry: string; title: string; body: string; savedOff: string; confirm: string }
export const sceneEffectsCopy: Record<Locale, Copy> = {
  en: { name: 'Scene effects', on: 'On · Fruit, splash, leaves & ice', off: 'Off · Product only', waiting: 'Loading your product first…', core: 'Preparing models, labels & avatars…', effects: 'Preparing scene effects…', error: 'Some images could not load.', retry: 'Click to retry', title: 'Your scene is ready', body: 'The images are loaded and the full scene is now on. Prefer a simpler view? Use Scene effects to hide or show the fruit, splash, leaves and ice anytime.', savedOff: 'The images are loaded. Your simpler view has been kept. Use Scene effects anytime to bring back the fruit, splash, leaves and ice.', confirm: 'Got it' },
  fr: { name: 'Effets de scène', on: 'Activés · Fruits, eau, feuilles et glace', off: 'Désactivés · Produit seul', waiting: 'Chargement du produit en premier…', core: 'Préparation des modèles, étiquettes et avatars…', effects: 'Préparation des effets de scène…', error: 'Certaines images n’ont pas pu être chargées.', retry: 'Cliquez pour réessayer', title: 'Votre scène est prête', body: 'Les images sont chargées et la scène complète est activée. Pour une vue plus simple, utilisez Effets de scène pour masquer ou afficher les fruits, l’eau, les feuilles et la glace.', savedOff: 'Les images sont chargées. Votre vue simplifiée est conservée. Activez Effets de scène pour retrouver les éléments décoratifs.', confirm: 'Compris' },
  zh: { name: '场景效果', on: '已开启 · 水果、水花、叶子和冰块', off: '已关闭 · 仅产品', waiting: '正在优先加载产品…', core: '正在准备模型、标签和头像…', effects: '正在准备场景效果…', error: '部分图片加载失败。', retry: '点击重试', title: '场景已准备就绪', body: '图片已加载，完整场景已开启。想要更简洁的视图？随时点击“场景效果”来隐藏或显示水果、水花、叶子和冰块。', savedOff: '图片已加载，并保留了您选择的简洁视图。随时开启“场景效果”以显示装饰元素。', confirm: '知道了' },
  es: { name: 'Efectos de escena', on: 'Activados · Frutas, agua, hojas y hielo', off: 'Desactivados · Solo producto', waiting: 'Cargando primero el producto…', core: 'Preparando modelos, etiquetas y avatares…', effects: 'Preparando efectos de escena…', error: 'Algunas imágenes no se pudieron cargar.', retry: 'Haz clic para reintentar', title: 'Tu escena está lista', body: 'Las imágenes están cargadas y la escena completa está activada. ¿Prefieres una vista más sencilla? Usa Efectos de escena para ocultar o mostrar frutas, agua, hojas y hielo cuando quieras.', savedOff: 'Las imágenes están cargadas. Hemos conservado tu vista sencilla. Activa Efectos de escena para volver a ver los elementos decorativos.', confirm: 'Entendido' },
  ar: { name: 'تأثيرات المشهد', on: 'مفعّلة · فواكه وماء وأوراق وثلج', off: 'متوقفة · المنتج فقط', waiting: 'يتم تحميل المنتج أولاً…', core: 'تجهيز النماذج والملصقات والصور…', effects: 'تجهيز تأثيرات المشهد…', error: 'تعذر تحميل بعض الصور.', retry: 'اضغط لإعادة المحاولة', title: 'المشهد جاهز', body: 'اكتمل تحميل الصور وتم تفعيل المشهد الكامل. لعرض أبسط، استخدم تأثيرات المشهد لإخفاء أو إظهار الفواكه والماء والأوراق والثلج في أي وقت.', savedOff: 'اكتمل تحميل الصور وتم الاحتفاظ باختيارك للعرض البسيط. فعّل تأثيرات المشهد لعرض العناصر الزخرفية.', confirm: 'فهمت' },
  ru: { name: 'Эффекты сцены', on: 'Вкл. · Фрукты, брызги, листья и лёд', off: 'Выкл. · Только продукт', waiting: 'Сначала загружается продукт…', core: 'Подготовка моделей, этикеток и аватаров…', effects: 'Подготовка эффектов сцены…', error: 'Некоторые изображения не загрузились.', retry: 'Нажмите, чтобы повторить', title: 'Сцена готова', body: 'Изображения загружены, полная сцена включена. Хотите более простой вид? Кнопка «Эффекты сцены» позволяет скрывать или показывать фрукты, брызги, листья и лёд.', savedOff: 'Изображения загружены. Ваш упрощённый вид сохранён. Включите «Эффекты сцены», чтобы вернуть декорации.', confirm: 'Понятно' },
  ko: { name: '장면 효과', on: '켜짐 · 과일, 물보라, 잎과 얼음', off: '꺼짐 · 제품만 표시', waiting: '제품을 먼저 불러오는 중…', core: '모델, 라벨과 이미지를 준비하는 중…', effects: '장면 효과를 준비하는 중…', error: '일부 이미지를 불러오지 못했습니다.', retry: '클릭하여 다시 시도', title: '장면이 준비되었습니다', body: '이미지를 불러왔으며 전체 장면이 켜졌습니다. 더 간단한 화면을 원하시면 장면 효과 버튼으로 과일, 물보라, 잎과 얼음을 언제든 숨기거나 표시할 수 있습니다.', savedOff: '이미지를 불러왔습니다. 선택하신 간단한 화면을 유지했습니다. 장면 효과를 켜면 장식 요소가 다시 표시됩니다.', confirm: '확인' },
  de: { name: 'Szeneneffekte', on: 'An · Früchte, Wasser, Blätter und Eis', off: 'Aus · Nur das Produkt', waiting: 'Das Produkt wird zuerst geladen…', core: 'Modelle, Etiketten und Bilder werden vorbereitet…', effects: 'Szeneneffekte werden vorbereitet…', error: 'Einige Bilder konnten nicht geladen werden.', retry: 'Zum Wiederholen klicken', title: 'Deine Szene ist bereit', body: 'Die Bilder sind geladen und die vollständige Szene ist aktiv. Für eine einfachere Ansicht kannst du mit Szeneneffekte jederzeit Früchte, Wasser, Blätter und Eis aus- oder einblenden.', savedOff: 'Die Bilder sind geladen. Deine einfache Ansicht bleibt erhalten. Aktiviere Szeneneffekte, um die Dekorationen wieder einzublenden.', confirm: 'Verstanden' },
};
