'use client';
import { useCallback,useEffect,useState } from 'react';
import { Activity,ArrowLeft,ArrowRight,Check,Download,Eye,LoaderCircle,MousePointer2,RefreshCw,ShieldCheck,TriangleAlert,Users } from 'lucide-react';
import type { CatalogData } from '@/lib/catalog/contracts';
import type { AnalyticsFilter,AnalyticsReport,LogFilter,LogReport,SecurityReport } from '@/lib/operations/contracts';
import { SECURITY_TYPES,USAGE_EVENTS } from '@/lib/operations/contracts';
import { operationRequest,operationUrl } from './api';
import { BarChart,TrendChart } from './Charts';
import styles from './operations.module.css';

const number=(value:number)=>new Intl.NumberFormat('vi-VN').format(value);
const date=(value:string)=>new Date(value).toLocaleString('vi-VN');
const query=(value:object)=>new URLSearchParams(Object.entries(value).map(([key,item])=>[key,String(item)])).toString();
function actionLabel(action:string){
  if(SECURITY_TYPES[action])return SECURITY_TYPES[action].label;
  const [verb,collection]=action.split(':');
  const verbs:Record<string,string>={http_request:'Request API',save:'Lưu',archive:'Lưu trữ',delete:'Xóa',reorder:'Đổi thứ tự',publish:'Phát hành',rollback:'Dùng lại phiên bản',acknowledge:'Xác nhận'};
  const collections:Record<string,string>={drinkTypes:'loại nước',packagingCategories:'nhóm bao bì',packagingVariants:'bao bì',flavors:'hương vị',flavorAssets:'pool ảnh',productGroups:'dòng sản phẩm',productVariants:'sản phẩm',packagingSlots:'slot bao bì',media:'file tài nguyên',labels:'cấu hình nhãn',models3d:'model 3D',assets2d:'model 2D',displays3d:'hiển thị 3D',displays2d:'hiển thị 2D',release:'lịch sử phát hành',alert:'cảnh báo'};
  return `${verbs[verb]||verb}${collection?` ${collections[collection]||collection}`:''}`;
}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`vinut-${name}-${new Date().toISOString().slice(0,10)}.json`;link.style.display='none';document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);}
function Metric({label,value,previous,icon:Icon,note}:{label:string;value:number;previous?:number;icon:typeof Eye;note?:string}){
  const change=previous?Math.round((value-previous)/previous*100):null;
  return <article className={styles.metric}><div><span>{label}</span><Icon size={19} aria-hidden="true"/></div><strong>{number(value)}</strong><small>{note|| (change===null?(previous===0?'Chưa có số liệu kỳ trước':'24 giờ gần nhất'):`${change>0?'+':''}${change}% so với kỳ trước`)}</small></article>;
}
export default function OperationsWorkspace({mode,catalog,canAcknowledge=false,onNavigate}:{mode:'overview'|'analytics'|'security';catalog:CatalogData;canAcknowledge?:boolean;onNavigate?:(module:'analytics'|'security')=>void}){
  const [filters,setFilters]=useState<AnalyticsFilter>({days:7,device:'all',scope:'all'});
  const [logFilters,setLogFilters]=useState<LogFilter>({kind:'security',severity:'all',days:1,page:1});
  const [analytics,setAnalytics]=useState<AnalyticsReport|null>(null),[security,setSecurity]=useState<SecurityReport|null>(null),[logs,setLogs]=useState<LogReport|null>(null);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[automatic,setAutomatic]=useState(true),[action,setAction]=useState('');
  const refresh=useCallback(async(signal?:AbortSignal)=>{
    setBusy(true);
    try{
      const responses=await Promise.all([
        mode!=='security'?operationRequest<AnalyticsReport>(`analytics?${query(filters)}`,{signal}):Promise.resolve(null),
        mode!=='analytics'?operationRequest<SecurityReport>('security',{signal}):Promise.resolve(null),
        mode==='security'?operationRequest<LogReport>(`logs?${query(logFilters)}`,{signal}):Promise.resolve(null),
      ]);
      if(signal?.aborted)return;
      if(responses[0])setAnalytics(responses[0]);if(responses[1])setSecurity(responses[1]);if(responses[2])setLogs(responses[2]);setError('');
    }catch(cause){if(!signal?.aborted)setError(cause instanceof Error?cause.message:'Không tải được dữ liệu vận hành.');}
    finally{if(!signal?.aborted)setBusy(false);}
  },[mode,filters,logFilters]);
  useEffect(()=>{
    const controller=new AbortController();let loading=false;
    const load=async()=>{if(loading||document.visibilityState==='hidden')return;loading=true;try{await refresh(controller.signal);}finally{loading=false;}};
    const initial=window.setTimeout(()=>void load(),0),timer=automatic?window.setInterval(()=>void load(),30000):null;
    if(automatic)document.addEventListener('visibilitychange',load);
    return()=>{controller.abort();window.clearTimeout(initial);if(timer)window.clearInterval(timer);document.removeEventListener('visibilitychange',load);};
  },[refresh,automatic]);
  async function acknowledge(id:string){setAction(id);try{await operationRequest('acknowledge',{body:{id}});await refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Không xác nhận được cảnh báo.');}finally{setAction('');}}
  async function exportLogs(){setAction('export');try{await operationRequest<LogReport>(`logs?${query(logFilters)}&export=1`);const link=document.createElement('a');link.href=operationUrl(`logs?${query(logFilters)}&export=1`);link.download='vinut-logs.json';document.body.appendChild(link);link.click();link.remove();}catch(cause){setError(cause instanceof Error?cause.message:'Không xuất được log.');}finally{setAction('');}}
  const loaded=mode==='security'?security:analytics;
  const filterLog=(value:Partial<LogFilter>)=>{setLogs(null);setLogFilters(current=>({...current,...value,page:1}));};
  const filterAnalytics=(value:Partial<AnalyticsFilter>)=>{setAnalytics(null);setFilters(current=>({...current,...value}));};
  if(mode==='overview')return <section className={styles.workspace}><div className={styles.overviewHeading}><div><p className={styles.eyebrow}>VẬN HÀNH WEBSITE</p><h2>Truy cập & giám sát</h2></div><div className={styles.actions}><button type="button" onClick={()=>onNavigate?.('analytics')}>Xem thống kê <ArrowRight size={16}/></button><button type="button" onClick={()=>onNavigate?.('security')}>An ninh & log <ShieldCheck size={16}/></button></div></div>{error&&<p className={styles.error} role="alert">{error}</p>}{analytics&&security?<><div className={styles.metrics}><Metric label="Lượt mở web · 7 ngày" value={analytics.totals.views} previous={analytics.previous.views} icon={Eye}/><Metric label="Phiên truy cập · 7 ngày" value={analytics.totals.sessions} previous={analytics.previous.sessions} icon={Users}/><Metric label="Tương tác · 7 ngày" value={analytics.totals.interactions} previous={analytics.previous.interactions} icon={MousePointer2}/><Metric label="Cảnh báo chưa xác nhận" value={security.totals.openAlerts} icon={ShieldCheck} note="Mở An ninh & log để xử lý"/></div>{!analytics.firstEventAt&&<p className={styles.note}>Chưa có sự kiện truy cập. Mở trang chính và thử chọn hương vị để bắt đầu ghi nhận.</p>}</>:<p className={styles.note}>{busy?'Đang tải dữ liệu vận hành…':'Chưa nhận được dữ liệu vận hành.'}</p>}</section>;
  return <section className={styles.workspace} aria-busy={busy}>
    <div className={styles.heading}><div><p className={styles.eyebrow}>VẬN HÀNH WEBSITE</p><h1>{mode==='analytics'?'Thống kê truy cập':'An ninh & log'}</h1><p>{mode==='analytics'?'Theo dõi truy cập và những chức năng khách dùng nhiều nhất.':'Theo dõi request API, phát hiện dấu hiệu bất thường và tra cứu thao tác quản trị.'}</p></div><div className={styles.actions}><button type="button" disabled={busy} onClick={()=>void refresh()}>{busy?<LoaderCircle size={17} className={styles.spin}/>:<RefreshCw size={17}/>}Tải lại</button>{mode==='analytics'&&analytics&&<button type="button" onClick={()=>download(analytics,'analytics')}><Download size={17}/>Xuất thống kê</button>}</div></div>
    <div className={styles.sync}><label><input type="checkbox" checked={automatic} onChange={event=>setAutomatic(event.target.checked)}/>Tự cập nhật mỗi 30 giây</label><span>{loaded?`Cập nhật: ${date(loaded.generatedAt)}`:'Đang kết nối dữ liệu'}</span></div>
    {error&&<p className={styles.error} role="alert">{error} {loaded&&'Đang giữ số liệu lần tải thành công gần nhất.'}</p>}
    {mode==='analytics'?<>
      <div className={styles.filters}><label>Khoảng thời gian<select value={filters.days} onChange={event=>filterAnalytics({days:Number(event.target.value) as AnalyticsFilter['days']})}><option value="1">24 giờ</option><option value="7">7 ngày</option><option value="30">30 ngày</option></select></label><label>Thiết bị<select value={filters.device} onChange={event=>filterAnalytics({device:event.target.value as AnalyticsFilter['device']})}><option value="all">Tất cả thiết bị</option><option value="desktop">Máy tính</option><option value="mobile">Điện thoại</option><option value="tablet">Máy tính bảng</option></select></label><label>Nguồn traffic<select value={filters.scope} onChange={event=>filterAnalytics({scope:event.target.value as AnalyticsFilter['scope']})}><option value="all">Tất cả nguồn</option><option value="local">Local / thử nghiệm</option><option value="production">Website online</option></select></label></div>
      {analytics&&<><div className={styles.metrics}><Metric label="Lượt mở website" value={analytics.totals.views} previous={analytics.previous.views} icon={Eye}/><Metric label="Phiên truy cập" value={analytics.totals.sessions} previous={analytics.previous.sessions} icon={Users}/><Metric label="Tương tác chức năng" value={analytics.totals.interactions} previous={analytics.previous.interactions} icon={MousePointer2}/><Metric label="Phiên có tương tác" value={analytics.totals.engagedSessions} previous={analytics.previous.engagedSessions} icon={Activity}/></div>
        {!analytics.totals.views&&!analytics.totals.interactions&&<div className={styles.notice}><Activity size={22}/><div><strong>Chưa có lượt truy cập trong bộ lọc này</strong><p>Mở website và dùng các chức năng để tạo số liệu thật. Dữ liệu cũ trước khi bật thống kê không được tính lại.</p></div></div>}
        <div className={styles.twoColumns}><article className={`${styles.panel} ${styles.wide}`}><h2>Truy cập theo thời gian</h2><p>Lượt mở trang và số phiên bắt đầu / có hoạt động tại từng mốc.</p><TrendChart rows={analytics.trend} series={[{key:'views',label:'Lượt mở',color:'var(--ops-green)'},{key:'sessions',label:'Phiên',color:'var(--ops-blue)'}]} hourly={filters.days===1}/></article><article className={styles.panel}><h2>Chức năng được dùng nhiều nhất</h2><p>Số lần người dùng chủ động thao tác.</p><BarChart rows={analytics.features.map(row=>({name:USAGE_EVENTS[row.name],count:row.count}))}/></article></div>
        <div className={styles.twoColumns}><article className={styles.panel}><h2>Hương vị được chọn</h2><BarChart rows={analytics.products.map(row=>({name:catalog.productVariants.find(item=>item.id===row.id)?.name||`ID: ${row.id}`,count:row.count}))}/></article><article className={styles.panel}><h2>Best seller được chọn</h2><BarChart rows={analytics.groups.map(row=>({name:catalog.productGroups.find(item=>item.id===row.id)?.buttonLabel||catalog.productGroups.find(item=>item.id===row.id)?.name||`ID: ${row.id}`,count:row.count}))}/></article></div>
        <div className={styles.twoColumns}><article className={styles.panel}><h2>Thiết bị truy cập</h2><BarChart rows={analytics.devices.map(row=>({name:({desktop:'Máy tính',mobile:'Điện thoại',tablet:'Máy tính bảng'} as Record<string,string>)[row.name]||row.name,count:row.count}))}/></article><article className={styles.panel}><h2>Ngôn ngữ khi mở website</h2><BarChart rows={analytics.languages.map(row=>({name:row.name.toUpperCase(),count:row.count}))}/></article></div>
        <p className={styles.note}>Phiên ẩn danh theo tab, hết hạn sau 30 phút không hoạt động; đây không phải số người chính xác. Thiết bị phân loại theo kích thước màn hình. Không tính bot đã nhận diện và trình duyệt bật Do Not Track. Lưu tối đa {analytics.retentionDays} ngày; dữ liệu có giới hạn dung lượng.</p>
      </>}
    </>:<>{security&&<>
      <div className={`${styles.notice} ${security.monitoring==='degraded'?styles.danger:''}`}><ShieldCheck size={22}/><div><strong>{security.monitoring==='active'?'Giám sát API đang hoạt động':'Giám sát có lỗi ghi log — cần kiểm tra backend'}</strong><p>Phạm vi: API trên server này. Request đến GitHub Pages và tấn công bị chặn trước API cần log từ hosting / reverse proxy. Cảnh báo là dấu hiệu cần kiểm tra, không xác nhận đã bị xâm nhập.</p></div></div>
      <div className={styles.metrics}><Metric label="Request API · 24 giờ" value={security.totals.requests} icon={Activity} note={`Thời gian xử lý trung bình ${security.totals.averageMs} ms`}/><Metric label="Request bị chặn" value={security.totals.blocked} icon={ShieldCheck}/><Metric label="Đăng nhập thất bại" value={security.totals.failedLogins} icon={Users}/><Metric label="Cảnh báo chưa xác nhận" value={security.totals.openAlerts} icon={TriangleAlert} note={`${security.totals.errors} request lỗi server (5xx)`}/></div>
      <article className={styles.panel}><div className={styles.sectionTitle}><div><h2>Cảnh báo cần theo dõi</h2><p>Xác nhận giữ lại log; khi nguồn đó tiếp tục vi phạm, cảnh báo sẽ mở lại.</p></div><span className={styles.badge}>{security.totals.openAlerts} chưa xác nhận</span></div><div className={styles.alerts}>{security.alerts.length?security.alerts.map(alert=><article key={alert.id} className={`${styles.alert} ${alert.acknowledgedAt?styles.acknowledged:alert.severity==='critical'?styles.danger:''}`}><div><span className={styles.badge}>{alert.acknowledgedAt?'Đã xác nhận':alert.severity==='critical'?'Mức cao':'Cần kiểm tra'}</span><h3>{SECURITY_TYPES[alert.type]?.label||alert.type}</h3><p>{SECURITY_TYPES[alert.type]?.help}</p><small>Nguồn ẩn danh: <code>{alert.source}</code> · {number(alert.count)} sự kiện trong cửa sổ phát hiện · Lần cuối: {date(alert.lastAt)}</small>{alert.acknowledgedAt&&<small>Xác nhận lúc {date(alert.acknowledgedAt)}</small>}</div>{!alert.acknowledgedAt&&<button type="button" disabled={!canAcknowledge||!!action} title={!canAcknowledge?'Chỉ chủ quản trị được xác nhận cảnh báo':undefined} onClick={()=>void acknowledge(alert.id)}>{action===alert.id?<LoaderCircle size={16} className={styles.spin}/>:<Check size={16}/>}Đã xem</button>}</article>):<div className={styles.empty}><ShieldCheck size={25}/><strong>Chưa phát hiện dấu hiệu vượt ngưỡng</strong><p>Log bên dưới vẫn ghi nhận các request và sự kiện riêng lẻ.</p></div>}</div></article>
      <article className={styles.panel}><h2>Request & lỗi API · 24 giờ</h2><TrendChart rows={security.trend} hourly series={[{key:'requests',label:'Request ghi log',color:'var(--ops-green)'},{key:'blocked',label:'Spam bị giới hạn',color:'var(--ops-amber)'},{key:'errors',label:'Lỗi 5xx',color:'var(--ops-red)'}]}/><p className={styles.note}>Access log lấy mẫu HTTP 429 mỗi 10 giây để tránh phình dữ liệu; bộ đếm cảnh báo vẫn đếm từng request bị giới hạn.</p></article>
      <article className={styles.panel}><div className={styles.sectionTitle}><div><h2>Nhật ký hoạt động</h2><p>Log đã loại mật khẩu, cookie, nội dung request, query URL và IP gốc.</p></div><button type="button" disabled={!!action} onClick={()=>void exportLogs()}><Download size={16}/>Xuất log JSON</button></div><div className={styles.filters}><label>Loại log<select value={logFilters.kind} onChange={event=>filterLog({kind:event.target.value as LogFilter['kind']})}><option value="security">Sự kiện an ninh</option><option value="request">Request API</option><option value="audit">Thao tác quản trị</option></select></label><label>Mức độ<select value={logFilters.severity} onChange={event=>filterLog({severity:event.target.value as LogFilter['severity']})}><option value="all">Tất cả mức độ</option><option value="info">Thông tin</option><option value="warning">Cần kiểm tra</option><option value="critical">Mức cao</option></select></label><label>Thời gian<select value={logFilters.days} onChange={event=>filterLog({days:Number(event.target.value) as LogFilter['days']})}><option value="1">24 giờ</option><option value="7">7 ngày</option><option value="30">30 ngày</option></select></label></div>
      {logs&&<><div className={styles.tableWrap}><table><thead><tr><th>Thời gian</th><th>Sự kiện / đường dẫn</th><th>Kết quả</th><th>Nguồn / người thao tác</th><th>Mã request</th></tr></thead><tbody>{logs.rows.map(log=><tr key={log.id}><td>{date(log.time)}</td><td><strong>{actionLabel(log.action)}</strong><code>{log.method} {log.route}</code></td><td><span className={`${styles.badge} ${log.severity!=='info'?styles.statusWarning:''}`}>{log.status||({info:'Thông tin',warning:'Cần kiểm tra',critical:'Mức cao'})[log.severity]}</span><small>{log.durationMs!==null?`${log.durationMs} ms`:`${log.count} sự kiện`}</small></td><td><code>{log.actor||log.source||'—'}</code></td><td><code>{log.requestId||'—'}</code></td></tr>)}</tbody></table>{!logs.rows.length&&<p className={styles.empty}>Không có log phù hợp bộ lọc.</p>}</div><div className={styles.pagination}><span>{number(logs.total)} dòng · Trang {logs.page}/{Math.max(1,Math.ceil(logs.total/logs.pageSize))}</span><button type="button" aria-label="Trang log trước" disabled={busy||logs.page<=1} onClick={()=>setLogFilters({...logFilters,page:logs.page-1})}><ArrowLeft size={17}/></button><button type="button" aria-label="Trang log sau" disabled={busy||logs.page*logs.pageSize>=logs.total} onClick={()=>setLogFilters({...logFilters,page:logs.page+1})}><ArrowRight size={17}/></button></div></>}
      </article><details className={`${styles.panel} ${styles.details}`}><summary>Quy tắc cảnh báo & lưu trữ</summary><ul className={styles.rules}>{security.rules.map(rule=><li key={rule.type}><strong>{SECURITY_TYPES[rule.type]?.label}</strong><span>≥ {rule.threshold} sự kiện / {rule.minutes} phút / nguồn</span></li>)}</ul><p className={styles.note}>Giới hạn: 240 request API / phút, 10 request đăng nhập / phút, 60 batch thống kê / phút / nguồn. HTTP 429 có Retry-After. Log vận hành lưu {security.retentionDays} ngày và có giới hạn số dòng; bản xuất tối đa 5.000 dòng theo bộ lọc. Không gửi thông báo email bên ngoài.</p></details>
    </>}</>}
    {!loaded&&!error&&<p className={styles.empty}><LoaderCircle size={20} className={styles.spin}/>Đang tải dữ liệu thật từ server…</p>}
  </section>;
}
